// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
....................
.....ffffffffff.....
....fff8ff88ffff....
...fffff8ff88ffff...
...fffddddddddfff...
...ffddfddddfddff...
...ffddfddddfddff...
...fbddfddddfddbf...
...fbddddddddddbf...
....fbbbbbbbbbbf....
.....ffffffffff.....
...ffff677776ffff...
...fddf677776fddf...
...fbbf666666fbbf...
...ffffffffffffff...
.....f88888888f.....
....ffff8888ffff....
...feeeeffffeeeef...
...ffffff..ffffff...
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
